version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  mysql:
    image: 'mysql:5.7.20'
    command: >
      --key_buffer_size=4m
      --query_cache_type=ON
      --query_cache_limit=8m
      --query_cache_size=32m
      --sort_buffer_size=4m
      --read_rnd_buffer_size=2m
      --innodb_buffer_pool_size=1g
    environment:
       MYSQL_DATABASE: site-template
       MYSQL_PASSWORD: qwerty
       MYSQL_ROOT_PASSWORD: qwerty
       MYSQL_USER: site
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data: {  }